### ISSUE TITLE
Cant download voices at all.

### ISSUE THREAD

**Issue by xrafy705** [tryreplay/replay-issues#13]
Stupid bug where when i press download it logs me out for 1 second then it refuses to download, everytime i press download out of nowhere theres a pop up for 1 second telling me to Log In or Sign Up then it goes away after my account reconnects. I cant do anything anymore idk why, stupid bug.

**Comment by RivMist** [comment]
Apologies for the inconvenience, I introduced a temporary bug. It should be fixed now!

**Comment by xrafy705** [comment]
thank you! it works like a charm again :)
