### ISSUE TITLE
Not an issue - suggestion to use random audio in preview

### ISSUE THREAD

**Issue by johndpope** [tryreplay/replay-issues#15]
I love the site - ui is slick - just some constructive feedback -

the "DRY" boring audio preview you get from https://www.weights.gg/
are monotenous after half a dozen clicks - 

when I click into the model - then preview from the side / the previews are so much richer - 
consider using a random selection from one of these instead of default one.

eg.
https://www.weights.gg/models/cloway05o06vmws63jjbk1r8p
![Screenshot from 2023-11-19 07-06-08](https://github.com/tryreplay/replay-issues/assets/289994/9d83e542-ee3b-4228-87a2-523a107c2e37)

**Comment by RivMist** [comment]
Great idea! We will see about adding a random playback track to avoid playing the same one over and over. Thanks for the suggestion :)
