### ISSUE TITLE
no valid .pth files found for selected model 

### ISSUE THREAD

**Issue by cclcng** [tryreplay/replay-issues#16]
Ive successfully done many generations with different models, but for some reason, I'm getting an error when trying to generate  with the marge simpson 4k voice. I deleted the local file and tried to redownload, but nothing is working. 

![marge simpson](https://github.com/tryreplay/replay-issues/assets/71544712/febcd807-f6a3-474c-80a3-dce81117a99b)

**Comment by jonluca** [comment]
Can you try with v3.0.0? This should be fixed
