### ISSUE TITLE
WHERE IS THE SEARCH BAR AND DOWNLOAD BUTTON ON WEIGHTS.GG!??!!?!?

### ISSUE THREAD

**Issue by That0neCloud** [tryreplay/replay-issues#17]
i have been losing my mind because i have tried to get a voice, tried to **find that voice**, **download** it, and use it for private reasons.
so, now, PLEASE JUST _**PLEASE**_ PUT BACK THE _**OLD UI**_, HOW DOES IT EVEN WORK?!??!?!

**Comment by RivMist** [comment]
Hey! What UI changes are you observing? Are you on mobile or desktop? We haven’t made any large changes to the UI, so this sounds like a bug. If you can share a screenshot and device specs we can fix. Thanks.
