### ISSUE TITLE
Download button just redirecting to model page

### ISSUE THREAD

**Issue by Fezezen** [tryreplay/replay-issues#18]
For whatever reason, just on this specific model, every time I click the download button, it just redirects me to the model page. I got it to download the zip file once, and I could have sworn all I did to do that was remove the whole "https://www.weights.gg/download?fileUrl=" part of the link, but now it just won't work.

This is the page where it happens
https://www.weights.gg/models/clm72tv4q0sg9cctc8ztnsis1

**Comment by jonluca** [comment]
Are you signed in?

**Comment by Fezezen** [comment]
Yes

**Comment by Fezezen** [comment]
https://github.com/tryreplay/replay-issues/assets/35386815/15ccb736-0625-4ba6-a709-5ed67930c1ab

**Comment by jonluca** [comment]
This should be fixed
