### ISSUE TITLE
Ubuntu. Replay can't make download and start, errors in the log

### ISSUE THREAD

**Issue by ersten** [tryreplay/replay-issues#24]
Ubuntu 22.10
Replay-3.2.4

There is an infinite loop with first dialog box (AI data download). Logs (cutted):

> [Server][2023-12-20 07:47:03] [info] - Server is downloading, not counting install as valid  
> [Server][2023-12-20 07:47:03] [info] - Checking file 35 of 35  
> [Server][2023-12-20 07:47:03] [info] - Fetching file 1 of 1  
> [Server][2023-12-20 07:47:03] [info] - Downloading dbbdb50737ef992504a63bd45d9874b91d94bcbf-linux-x64-pyinstaller6.zip  
> [Server][2023-12-20 07:47:03] [info] - Decompressing file 1 of 1  
> [Server][2023-12-20 07:47:04] [info] - Download complete  
> [Server][2023-12-20 07:47:04] [info] - Server is downloading, not counting install as valid  
> [Server][2023-12-20 07:47:04] [info] - Python server not valid, not starting  
> [Server][2023-12-20 07:47:04] [info] - File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0  
> [Server][2023-12-20 07:47:05] [info] - File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0  
> [Server][2023-12-20 07:47:06] [info] - File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0  
> [Server][2023-12-20 07:47:07] [info] - File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0  
> [Server][2023-12-20 07:47:08] [info] - File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0 
> 

File `..../server/_internal/torch/bin/protoc` exists, but `protoc-3.13.0.0` doesn't exists. 
Symlink `protoc-3.13.0.0` -> `protoc` doesn't work, CRC doesn't match.

Please help

**Comment by jonluca** [comment]
Try v3.7.3
