### ISSUE TITLE
GUI visual bug

### ISSUE THREAD

**Issue by alvar036** [tryreplay/replay-issues#29]
I got this weird bug on the windows version where it does some strange things to the UI
Especially when u scroll or navigate the interface.

it resets back to normal once u click outside the UI or resize it.

![replay_gui_bug](https://github.com/tryreplay/replay-issues/assets/121599180/93ae18c6-bbe4-4763-94a5-842bef1c95b2)

**Comment by alvar036** [comment]
still happening on v3.3.3

is anyone checking this?!

**Comment by jonluca** [comment]
Try v3.7.3
