### ISSUE TITLE
An error will occur if there are more than 6 songs

### ISSUE THREAD

**Issue by FanXiangTM** [tryreplay/replay-issues#30]
An error will occur if there are more than 6 songs, and all created songs need to be deleted to continue working.

**Comment by jonluca** [comment]
Can you show the error?

**Comment by FanXiangTM** [comment]
> 你能显示错误吗？

![Uploading 08-17.jpg…]()

**Comment by FanXiangTM** [comment]
> 你能显示错误吗？

![Uploading 08-17.jpg…]()

**Comment by FanXiangTM** [comment]
> 你能显示错误吗？

![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2cd8697a766514ef199dddb17e07f5039.jpg)

**Comment by FanXiangTM** [comment]
> Can you show the error?

rror creating song: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:376 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 2985984

**Comment by jonluca** [comment]
Try v3.7.3
