### ISSUE TITLE
no valid .pth files found for selected model！！！

### ISSUE THREAD

**Issue by EdenBush** [tryreplay/replay-issues#32]
![image](https://github.com/tryreplay/replay-issues/assets/79558861/33590e77-ed14-49c2-b938-bf9fabffd2cf)
no valid .pth files found for selected model！！！

**Comment by EdenBush** [comment]
Only a few models can be used normally, but most models have the problem of not being able to find the model, and re downloading is also ineffective

**Comment by EdenBush** [comment]
The downloaded version is the latest version 3.3.0

**Comment by jonluca** [comment]
Is this happening with models you found from the list inside replay?

**Comment by EdenBush** [comment]
> 您从重播列表中找到的模型会发生这种情况吗？

Yeah

**Comment by EdenBush** [comment]
> 您从重播列表中找到的模型会发生这种情况吗？

It doesn't matter, I used other models to achieve the same effect, only a few models

**Comment by EdenBush** [comment]
> 您从重播列表中找到的模型会发生这种情况吗？

It doesn't matter, I used other models to achieve the same effect, only a few models

**Comment by jonluca** [comment]
Yeah that's a known issue - we need to filter that model list to only valid models
