### ISSUE TITLE
Error on v3.5.3

### ISSUE THREAD

**Issue by Amirhosseinzandi-web** [tryreplay/replay-issues#37]
![Screenshot 2024-02-13 224228](https://github.com/tryreplay/replay-issues/assets/104035009/9f7a96ad-1b63-4570-8508-fa92af864b7d)

![Screenshot 2024-02-14 000335](https://github.com/tryreplay/replay-issues/assets/104035009/897d6dbd-847d-45b8-ac02-fce7a744c2b2)

I removed the local server and downloaded it again, but it's not solved. What should I do? I use Windows 11.

**Comment by jonluca** [comment]
Try v3.7.3
