### ISSUE TITLE
MacBook with M chip, can't delete duplicate files

### ISSUE THREAD

**Issue by ada578** [tryreplay/replay-issues#39]
！[上传截屏2024-02-29 11.50.37.png...]()"I tried deleting the entire Replay folder and then redownloading, but it still doesn't work.

**Comment by ada578** [comment]
[
![Uploading 截屏2024-02-29 11.50.37.png…]()
](url)

**Comment by ada578** [comment]
[hasRequiredFiles]: EEXIST: file already exists, symlink '/Users/zitiandexiaodiannao/Library/Application Support/Replay/com.replay.Replay/server/_internal/torch/lib/libtorch_python.dylib' -> 
'/Users/zitiandexiaodiannao/Library/Application Support/Replay/com.replay.Replay/server/_internal/libtorch_python.dylib'

**Comment by jonluca** [comment]
Please try v3.7.3
