### ISSUE TITLE
replay ubuntu 22.04 - stuck in download loop

### ISSUE THREAD

**Issue by johndpope** [tryreplay/replay-issues#40]
![Screenshot from 2024-03-01 10-33-30](https://github.com/tryreplay/replay-issues/assets/289994/b5a35704-bfe1-4044-9281-11a41d014378)
![Screenshot from 2024-03-01 10-32-44](https://github.com/tryreplay/replay-issues/assets/289994/c509b6e6-e731-49f4-b88c-57f3cb6fc040)
![Screenshot from 2024-03-01 10-32-37](https://github.com/tryreplay/replay-issues/assets/289994/d7d008b2-7dc0-4191-b776-e9e44d05fe84)

says decompressing final zip  - but then it just goes back to the first one.

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/fbfc69e2990f6823dfb96206acfba50c

**Comment by jonluca** [comment]
Ah this might be an ubuntu specific issue, let me take a look

**Comment by ersten** [comment]
Have the same issue with v3.7.3 + ubuntu

stuck in endless loop with downloading, looks like something wrong with protoc:
`File not found: /home/ersten/.config/Replay/com.replay.Replay/server/_internal/torch/bin/protoc-3.13.0.0 `

**Comment by CraftMaster163** [comment]
same issue on mint edge

**Comment by johndpope** [comment]
throw the download code into claude3-opus - it won't waste your time. has 200k context - can handle a lot of code - will find problem very quickly.

**Comment by THX2112** [comment]
Same issue with Windows 10.

**Comment by RodTDai** [comment]
same think linux mint

**Comment by stevethorson** [comment]
same on macOS 14

**Comment by KennyG5000** [comment]
I am having the same download issue on Windows on both 3.9.2 and 3.9.1, tried multiple times but the download just keeps restarting after it has finished (the continue button remains greyed out). If I restart Replay, it just begins the download again. I do get an error message saying 'EBUSY: resource busy or locked' rename. I have attached a screenshot of error if that is any help thanks.
![Replay Error](https://github.com/tryreplay/replay-issues/assets/40886780/4bcd12e6-09c4-4439-b641-4c473f493825)

**Comment by jasonstetson** [comment]
I have the same problem: Windows 10!!! fix it

**Comment by jonluca** [comment]
Can you try v3.9.4?

**Comment by ersten** [comment]
Finally v3.10.1 works fine with Ubuntu 22.04!
@jonluca thank you so much for you work!

**Comment by KennyG5000** [comment]
I can confirm  v3.10.1 is now working correctly here on Windows 10, thanks very much for applying such a quick fix, software looks amazing!
