### ISSUE TITLE
Error creating song: 'ModelData' object has no attribute 'mdx_n_fft_scale_set'

### ISSUE THREAD

**Issue by PumpkinSheee** [tryreplay/replay-issues#42]
Error creating song: 'ModelData' object has no attribute 'mdx_n_fft_scale_set'

tf does this mean

**Comment by jonluca** [comment]
what stem model were you trying to use

**Comment by vannoo67** [comment]
I have the same problem. Using Windows 10, Replay version downloaded today.
I have tried the following stem models from weights.gg 
  Cher (Country Version), Dean Martin, Eddie Vedder (Pearl Jam), Joni Mitchell

Can you recommend a known good model?

**Comment by jonluca** [comment]
What stem model are you trying to use

**Comment by vannoo67** [comment]
I don't know what a stem model is. I assume that you are talking about the voice model downloaded from weights.gg. 
I have tried 4, all failed with the same error.
They are; Cher (Country Version), Dean Martin, Eddie Vedder (Pearl Jam), Joni Mitchell

The interface refers to these as RVC models, is the stem model something else?

**Comment by jonluca** [comment]
In the Settings above where you click Create Cover there should be a stem model selection. What does it say?

**Comment by vannoo67** [comment]
I see. It is the default 'UVR-MDX-NET Voc FT'

**Comment by vannoo67** [comment]
Just installing/downloading latest version. I'll try ASAP

**Comment by vannoo67** [comment]
Probably shouldn't have done that. It now complains
Failed to load dynlib/dll ......libtorchaudio.pyd Most likely this dynlib/dll was not found when the application was frozen.

Should I un-install / re-install?

**Comment by jonluca** [comment]
Ah that's a new bug unfortunately - you can try going back to the previous version using https://www.tryreplay.io/versions

What operating system are you using? 

I'm pushing a fix for that now but it'll take an hour or so to go out

**Comment by vannoo67** [comment]
I'll try installing the old version.
I'm on Windows 10 (fresh install)

**Comment by vannoo67** [comment]
OK, re-installed old version, it re-downloaded 3+ GB of models, didn't change any settings, worked first time
