### ISSUE TITLE
Unable to connect to Server or see the downlaoded modules in Replay

### ISSUE THREAD

**Issue by 76Records** [tryreplay/replay-issues#46]
Hello guys!

First congrats on this amazing Ai software. I discovered Replay today and wanted to give it a try. Went on and downlaod on my Windows 11 Pro. After installation, I got the prompt to downlaod the files, I before change the Download path to another HDD and after files were downlaoded, Replay does NOT see the downlaoded file, in other word, I don't see the Category files as it should be and seem that its not connecting to the server. I did "Remove Local Server" and restart Replay to download back again the files but still same issue. 

Any help would be very much welcome. Thanks

**Comment by jonluca** [comment]
Youc an download the voices from https://www.weights.gg/ and then import them to replay

**Comment by 76Records** [comment]
> Youc an download the voices from https://www.weights.gg/ and then import them to replay

Hello Jon!
Thanks for your quick reply. By curiosity, is there a reason why the "Downloaded files" aren't showing in Replay that we have to take the manual option of downloading the "voices" from the link you shared with me??

Reason I'm asking is that I saw a video Tutorial on youtube and it seems that when you loaded additional voices at https://www.weights.gg/ , you have to always go and rename them wich  will make the process longer no be able to categorize them no??

Thanks for your help
