### ISSUE TITLE
Does Replay collect data about the RVC model used by the user and the generated songs

### ISSUE THREAD

**Issue by shenzheyuy** [tryreplay/replay-issues#47]
Dear developer, I am a new singer with a unique voice, because I can't speak Japanese, so I generated several Japanese songs on Replay with my personal RVC model trained by myself,I am worried about my voice being collected by others for various purposes, but the Replay agreement does not seem to mention the copyright protection of relevant aspects, so I would like to ask you specifically.
I appreciate your reply.

**Comment by jonluca** [comment]
Models from Replay are never shared externally. You would have to manually upload it to https://www.weights.gg/ or to your google drive and share it that way. Anything that happens on replay lives only on your machine and is 100% private. The only way to share anything in the app at all is to use the "Share Track" for a given creation, but that is a manual action and only for the audio, not for the model.
