### ISSUE TITLE
mdx_dim_f_set is giving this error.

### ISSUE THREAD

**Issue by AsilMediaUzbek** [tryreplay/replay-issues#56]
Hello! I just installed the program on my computer. But I can't create a model. mdx_dim_f_set is giving this error.
![screen](https://github.com/tryreplay/replay-issues/assets/40468520/0007bdc4-2213-4fec-8099-8d4edf277f86)
I downloaded the audio in both mp3 and wav formats. My computer is powerful enough: i7 11800h; 3060 RTX. System: Windows 10; Software version 4.1.3

**Comment by shradee** [comment]
agree, the same issue on rtx 3060 + r5 5600h, same version. Tried 4.1.2 and 4.1.1. both had the same result

**Comment by balina100** [comment]
I have that same problem: "modeldata" object has no attribute "mdx_dim_f_set"

**Comment by adelimary** [comment]
I have that same problem !!

**Comment by hayamiyui** [comment]
Yes, I also encountered this issue. I am unable to train a new model, even if I downgrade it. Currently, I am using versions 4.1.3 and 4.1.1, but I am not sure if 4.1.0 has the ability to train models. Maybe it does, I have forgotten.
There is one more thing, why do developers not package the model into the software and have to manually download it every time? This is very troublesome, especially if the network is not good.

**Comment by hayamiyui** [comment]
> Yes, I also encountered this issue. I am unable to train a new model, even if I downgrade it. Currently, I am using versions 4.1.3 and 4.1.1, but I am not sure if 4.1.0 has the ability to train models. Maybe it does, I have forgotten. There is one more thing, why do developers not package the model into the software and have to manually download it every time? This is very troublesome, especially if the network is not good.

4.1.0 still has this issue...

**Comment by truefriend-cz** [comment]
Version 4.2.4 same problem.
