### ISSUE TITLE
Server Download issue

### ISSUE THREAD

**Issue by TXCReeseedrianed** [tryreplay/replay-issues#63]
![image](https://github.com/user-attachments/assets/b8dc62ab-0831-48e1-94d6-cdd79cefac29)
I've been getting this issue whenever i'm downloading Replay AI. I've uninstalled it and reinstalled it and this error popped up. Is there a fix for it?

**Comment by jonluca** [comment]
Can you try v4.2.8

**Comment by XiChenBaBa** [comment]
Same issue in v4.28

**Comment by NicholasBly** [comment]
Same issue here, newest update too

**Comment by naf1111** [comment]
hi
server no work same error 4.3.0

**Comment by naf1111** [comment]
you can fix error

**Comment by sikorak666** [comment]
4.3.0 same error

**Comment by DmuzV** [comment]
I have the same problem when downloading and installing models... =/
