### ISSUE TITLE
4.4.2 Error: Request failed with status code 422 when I try to train new model

### ISSUE THREAD

**Issue by sotger** [tryreplay/replay-issues#66]
Audio for training - wav 48000 Hz 32 bit and mp3 - both unsuccessful.
RePlay app version 4.4.2 for macOS.
macOS Sonoma 14.6

**Comment by rgnestle** [comment]
It's too bad they don't have an answer for this. I am also getting a 422 error and can't find any information on it except your support request here. Sigh....

**Comment by Celso-Paulo** [comment]
Same problem here

**Comment by rgnestle** [comment]
Same here. This is ridiculous.

**Comment by rgnestle** [comment]
I've found that I don't get this message on my iMac running Windows 10. I DO get it on my Macbook Pro however. Still no word as to why. Both are 2019 models, but my Macbook Pro has a better graphics card (I believe it does, anyway.) The model is currently training in Windows, but still a 422 error on Mac. It must be a programming error or the AI downloads may not install properly on a Mac. So, how do we REinstall the AI downloads???
