### ISSUE TITLE
Error creating model.

### ISSUE THREAD

**Issue by DarkAlchy** [tryreplay/replay-issues#68]
Error creating model: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

I have a 4090, and I train Stable Diffusion with OneTrainer, and Kohya, and I have never had this error before with them.

**Comment by DarkAlchy** [comment]
Still no answer to this issue?

**Comment by jackdiy** [comment]
I am experiencing the same issue, and it is likely caused by the lack of support for CUDA 12. I was able to use CUDA 11 before, but my question is whether it’s possible to make it compatible with CUDA 11, as it seems that manually upgrading the relevant components via Pip is not possible

**Comment by DarkAlchy** [comment]
> I am experiencing the same issue, and it is likely caused by the lack of support for CUDA 12. I was able to use CUDA 11 before, but my question is whether it’s possible to make it compatible with CUDA 12, as it seems that manually upgrading the relevant components via Pip is not possible

This dev seems eerily absent and quiet.
