### ISSUE TITLE
Replsay will not load file, due tyo error

### ISSUE THREAD

**Issue by Princeus4545** [tryreplay/replay-issues#76]
error code for Replay Ai
<img width="1470" alt="Screenshot 2024-11-08 at 1 47 28 PM" src="https://github.com/user-attachments/assets/4c03c217-1fb3-40d9-bf99-ec8efdb1475f">

**Comment by Princeus4545** [comment]
load error on Replay ai

**Comment by jonluca** [comment]
it looks like the folder you selected in settings is incorrect
