### ISSUE TITLE
Where are the release notes?

### ISSUE THREAD

**Issue by IndustrialOne** [tryreplay/replay-issues#81]
There's no proper page for Replay with a changelog, announcements, guides, FAQs and so on. Can a dev release the release notes/bugfixes for the latest versions so we can follow the development?

**Comment by jonluca** [comment]
There are no release notes currently. You can follow along in the discord for updates and information.

**Comment by IndustrialOne** [comment]
> There are no release notes currently. You can follow along in the discord for updates and information.

Updates for Replay are not posted in the Discord either.
