### ISSUE TITLE
Search bar getting stuck

### ISSUE THREAD

**Issue by fredbrutus** [tryreplay/replay-issues#86]
Windows 11, replay 4.4.2

Bug when selecting part of YouTube videos:

In some cases, when trying to select the part where I want the video to be cut, the search bar gets stuck, so when I move the mouse the bar moves with it, not allowing the final selection. When this happens, I have tried several actions and I can't release the bar from the mouse pointer, only closing the application solves everything.

I have noticed this problem in previous versions.

**Comment by jonluca** [comment]
Make sure you are on the latest version of replay. (6.2.4)
