### ISSUE TITLE
Bug in BATCH song creation

### ISSUE THREAD

**Issue by didarocha** [tryreplay/replay-issues#9]
After a new song is created, it is normally added to the list at the left region of the app.
However, when several songs are created with the Batch button, only the first one is added to the list. The others have to be accessed by the windows explorer.

![bug](https://github.com/tryreplay/replay-issues/assets/148439270/f147c3c2-df2f-4dd6-aede-c196e000b914)

**Comment by jonluca** [comment]
You can view the batches in the view of the song
